exports.FETCH_START_LOCATION = 'FETCH_START_LOCATION';
exports.FETCH_START_LOCATION_SUCCESS = 'FETCH_START_LOCATION_SUCCESS';
exports.FETCH_START_LOCATION_ERROR = 'FETCH_START_LOCATION_ERROR';

exports.FETCH_CURRENT_LOCATION = 'FETCH_CURRENT_LOCATION';
exports.FETCH_CURRENT_LOCATION_SUCCESS = 'FETCH_CURRENT_LOCATION_SUCCESS';
exports.FETCH_CURRENT_LOCATION_ERROR = 'FETCH_CURRENT_LOCATION_ERROR';
exports.SEND_CURRENT_LOCATION = 'SEND_CURRENT_LOCATION';
exports.SEND_CURRENT_LOCATION_SUCCESS = 'SEND_CURRENT_LOCATION_SUCCESS';
exports.SEND_CURRENT_LOCATION_ERROR = 'SEND_CURRENT_LOCATION_ERROR';
exports.SEND_CURRENT_LOCATION_REQUEST = 'SEND_CURRENT_LOCATION_REQUEST';

exports.SET_USER_DESTINATION = 'SET_USER_DESTINATION';
exports.UPDATE_DURATION = 'UPDATE_DURATION';
exports.UPDATE_CONTACTS = 'UPDATE_CONTACTS';
exports.LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
exports.LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
exports.SET_MESSAGE = 'SET_MESSAGE';

exports.START_RUN = 'START_RUN';
exports.START_RUN_SUCCESS = 'START_RUN_SUCCESS';
exports.START_RUN_ERROR = 'START_RUN_ERROR';
exports.START_RUN_REQUEST = 'START_RUN_REQUEST';
