exports.FETCH_USER_LOCATION = 'FETCH_USER_LOCATION';
exports.FETCH_USER_LOCATION_SUCCESS = 'FETCH_USER_LOCATION_SUCCESS';
exports.FETCH_USER_LOCATION_ERROR = 'FETCH_USER_LOCATION_ERROR';
exports.SET_USER_DESTINATION = 'SET_USER_DESTINATION';
exports.UPDATE_DURATION = 'UPDATE_DURATION';
exports.UPDATE_CONTACTS = 'UPDATE_CONTACTS';
exports.LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
exports.LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
